export const POPULAR_CODE_LANGUAGES = [
  "plain",
  "text",
  "plaintext",
  "javascript",
  "js",
  "typescript",
  "ts",
  "jsx",
  "tsx",
  "html",
  "xml",
  "css",
  "scss",
  "sass",
  "less",
  "json",
  "jsonc",
  "yaml",
  "yml",
  "toml",
  "ini",
  "markdown",
  "md",
  "latex",
  "tex",
  "python",
  "py",
  "java",
  "c",
  "cpp",
  "c++",
  "csharp",
  "cs",
  "go",
  "golang",
  "rust",
  "rs",
  "php",
  "ruby",
  "rb",
  "kotlin",
  "kt",
  "swift",
  "dart",
  "scala",
  "r",
  "matlab",
  "julia",
  "lua",
  "perl",
  "objectivec",
  "objc",
  "haskell",
  "hs",
  "ocaml",
  "clojure",
  "elixir",
  "erlang",
  "fsharp",
  "fs",
  "sql",
  "mysql",
  "postgresql",
  "pgsql",
  "sqlite",
  "plsql",
  "bash",
  "sh",
  "shell",
  "zsh",
  "fish",
  "powershell",
  "ps1",
  "bat",
  "cmd",
  "dockerfile",
  "docker",
  "nginx",
  "apache",
  "graphql",
  "gql",
  "regex",
  "diff",
  "patch",
  "makefile",
  "cmake",
  "gradle",
  "groovy",
  "solidity",
  "wasm",
  "webassembly",
  "verilog",
  "vhdl",
  "assembly",
  "asm",
  "x86asm",
  "armasm",
  "http",
  "rest",
  "protobuf",
  "proto",
  "csv",
  "properties",
  "vue",
  "svelte",
  "astro",
  "twig",
  "handlebars",
  "hbs",
  "pug",
  "ejs",
  "liquid",
  "nix",
  "terraform",
  "hcl",
  "ansible",
  "stata",
  "sas",
  "scheme",
  "lisp",
  "common-lisp",
  "racket",
  "fortran",
  "pascal",
  "delphi",
  "basic",
  "vbnet",
  "visual-basic",
  "excel",
  "vba",
  "applescript",
  "gdscript",
  "godot",
  "processing",
  "arduino",
  "abap",
  "apex",
  "crystal",
  "nim",
  "zig",
  "reasonml",
  "rescript",
  "elm",
  "coffeescript",
  "livescript",
  "stylus",
  "postcss",
] as const;

export function normalizeCodeLanguage(language: string | undefined): string {
  const value = (language ?? "").trim().toLowerCase();

  if (!value) {
    return "plain";
  }

  if (value === "c++") return "cpp";
  if (value === "py") return "python";
  if (value === "js") return "javascript";
  if (value === "ts") return "typescript";
  if (value === "golang") return "go";
  if (value === "rs") return "rust";
  if (value === "rb") return "ruby";
  if (value === "kt") return "kotlin";
  if (value === "ps1") return "powershell";
  if (value === "sh" || value === "shell") return "bash";
  if (value === "md") return "markdown";
  if (value === "tex") return "latex";
  if (value === "yml") return "yaml";
  if (value === "docker") return "dockerfile";

  return value;
}
